### ISSUE TITLE
Issue on sending both privmsg and notice

### ISSUE THREAD

**Issue by sonots** [choplin/fluent-plugin-irc#9]
Sorry, but I just noticed that writing conf as followings does not work:

```apache
  <match notice.**>
    type irc
    host "#{ENV['IRC_SERVER']}"
    port 6667
    nick daioikachan
    user daioikachan
    real daioikachan
    command notice
    message %s
    out_keys message
  </match>
  <match privmsg.**>
    type irc
    host "#{ENV['IRC_SERVER']}"
    port 6667
    nick daioikachan
    user daioikachan
    real daioikachan
    command priv_msg
    message %s
    out_keys message
  </match>
```

This is because `nick` is the same for both `notice` and `priv_msg`. If we differentiate nick names, we can send both `notice` and `priv_msg`, but this was not my intend in pull request https://github.com/choplin/fluent-plugin-irc/pull/6

So, now I am thinking to change spec as either of:

```
  <match notice.**>
    type irc
    host "#{ENV['IRC_SERVER']}"
    port 6667
    nick daioikachan
    user daioikachan
    real daioikachan
    message %s
    out_keys privsmg  # send privmsg if record['privmsg'] exists
    notice_message %s
    notice_keys notice # send notice if record['notice'] exists
  </match>
```

or

```
  <match notice.**>
    type irc
    host "#{ENV['IRC_SERVER']}"
    port 6667
    nick daioikachan
    user daioikachan
    real daioikachan
    command %s
    command_keys command # dynamically assign `privmsg` or `notice` from record['command']
    message %s
    out_keys message
  </match>
```

I am currently implementing with the 2nd way, but can you tell me your opinion?

**Comment by sonots** [comment]
Another option is to share the same TCP connection if triples of host, port, nick is the same.

**Comment by choplin** [comment]
I understand the problem. IMO, the third option (i.e. shared connection for the same host, port and nick) because no extra option is added.
However, it is require to share a connection between multiple plugin instances. It cannot be implemented simply.
Do you have an idea about how to implement it?

**Comment by sonots** [comment]
I agree that the implementation of the 3rd option will be complex. 
As a final thought of mine, I think the 2nd option is the best among these three, so pull requested based on the 2nd option. Please check it out.
